---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 3534014118-feB8I59ld9OSr97TqwZNAs8bB517IcIUQQkDupk
:access_token_secret: xju8A6wVaFop24tPLHH2ZePXdplAi6EE5L1mSe3zoVaNZ
